config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"

  get '/', to: redirect('/posts')

  resources :users, only: [:create]
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"

  get "/posts", to: "posts#index"
  get "/posts/new", to: "posts#new", as: :new_post_path
  get "/posts/:id/edit", to: "posts#edit", as: :edit_post_path
  patch "/posts/:id/update", to: "posts#update", as: :update_post_path
  delete "/post/:id/delete", to: "posts#delete", as: :delete_post_path
  post "/posts", to: "posts#create"
  get "/post/:id", to: "posts#show", as: :post

  post "/comments", to: "comments#create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/partials/_header.html.erb
<% if logged_in? %>
  Hello
  <%= current_user.username %>
  <% if PostsCreationPolicy.create?(current_user)%>
  <%= link_to 'Create new post', new_post_path_url %>
  <% end %>
  <%= form_with url: sessions_path, method: :delete do |form| %>
    <%= form.submit "Sign out", class: "link-button" %>
  <% end %>
<% else %>
  <%= link_to "Log In", login_path %>
  <%= link_to "Sign Up", signup_path %>
<% end %>

app/views/partials/_search.html.erb
<%= form_tag posts_path, method: :get do %>
  <%= label_tag "title:" %>
  <%= text_field_tag(:title, params[:title], {placeholder: "title"}) %>
  <%= label_tag "author:" %>
  <%= select_tag(:author_username, options_for_select(usernames_that_have_posts, params[:author_username]), {include_blank: true, onchange: 'this.form.submit();'}) %>
  <br>
  <%= label_tag "tags:" %>
  <ul>
  <% tag_names_that_have_posts.each do |tag| %>
    <li>
      <%= check_box_tag(:"tag_titles[#{tag}]", 1, params[:tag_titles]&.keys&.include?(tag), onchange: 'this.form.submit();') %>
      <%= tag %>
    </li>
  <% end%>  
  </ul>
  <%= submit_tag "Search"%>
<% end %>