config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"

  get '/', to: redirect('/posts')

  resources :users, only: [:create]
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"

  get "/posts", to: "posts#index"
  get "/posts/new", to: "posts#new", as: :new_post_path
  get "/posts/:id/edit", to: "posts#edit", as: :edit_post_path
  patch "/posts/:id/update", to: "posts#update", as: :update_post_path
  delete "/post/:id/delete", to: "posts#delete", as: :delete_post_path
  post "/posts", to: "posts#create"
  get "/post/:id", to: "posts#show", as: :post

  post "/comments", to: "comments#create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :user, foreign_key: 'author_id', class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates :author, presence: true
  validates :title, presence: true, allow_blank: false
  validates :body, presence: true, allow_blank: false

  scope :title_search, ->(title) { where("title LIKE ?", "%#{title}%") }
  scope :author_search, ->(author_username) { includes(:author).where(author: {username: author_username}) }
  scope :tags_search, ->(tag_titles) { includes(:tags).where({tags: {name: tag_titles}}) }

  paginates_per 10

  accepts_nested_attributes_for :comments

  #accepts_nested_attributes_for does not support find_or_create_by
  def tag_names_array=(attrs)
    return unless attrs
    existing_tags = attrs.map{|attr| Tag.find_or_create_by(name: attr)}
    self.tags = existing_tags
  end

  def tag_names_with_commas
    tags.map(&:name).join(',')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorized
  def index
    @posts = PostsQueryService.call(normalized_search_params).page params[:page]
  end

  def show
    @post = Post.find_by(id_param)
  end

  def edit
    @post = Post.find_by(id_param)
  end

  def update
    post = Post.find_by(id_param)
    if PostsUpdatePolicy.update?(current_user, post)
      PostsUpdateService.call(post, normalized_post_params)
      redirect_to edit_post_path_url(post.id)
    end
  end
  
  def delete
    post = Post.find_by(id_param)
    if PostsDeletionPolicy.delete?(current_user, post)
      PostsDeletionService.call(post)
      redirect_to posts_path
    end
  end

  def new
    @post = Post.new
  end
  
  def create
    if PostsCreationPolicy.create?(current_user)
      post = PostsCreationService.call(current_user, normalized_post_params)
      redirect_to post_path(post)
    end
  end

  private

  def id_param
    params.permit(:id)
  end

  def normalized_post_params
    normalized_post_params = {}
    normalized_post_params[:title] = post_params[:title]
    normalized_post_params[:body] = post_params[:body]
    normalized_post_params[:tag_names_array] = post_params[:tag_names_array]&.split(',')
    normalized_post_params
  end

  def post_params
    params.require(:post).permit(:title, :body, :tag_names_array)
  end

  def search_params
    params.permit(:title, :author_username, :tag_titles => {})
  end

  def normalized_search_params
    normalized_search_params = {}
    normalized_search_params[:title] = search_params[:title]
    normalized_search_params[:author_username] = search_params[:author_username]
    normalized_search_params[:tag_titles] = search_params[:tag_titles]&.keys
    normalized_search_params
  end
end

app/views/posts/edit.html.erb
<td><%= link_to 'Back to posts', posts_path %><td>
<br>
<%= form_for @post, url: update_post_path_url(@post.id) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, placeholder: "title" %>
  <%= f.label :body %>
  <%= f.text_area :body, placeholder: "body" %>
  <%= f.label :tags %>
  <%= f.text_field :tag_names_array, {value: @post.tag_names_with_commas, placeholder: "tags"} %>
  <%= f.submit "Update Post" %>
<% end %>

app/views/posts/index.html.erb
<%= render partial: 'partials/search' %>
<br>
<table class="table table-hover">
<tr>
  <th>Title</th>
  <th>Tags</th>
  <th>Author</th>
  <th>Comments</th>
</tr>
<% @posts.each do |post| %>
  <tr>
    <td><%= link_to post.title, post_path(post.id) %><td>
    <td><%= post.tags.map(&:name).join(', ') %><td>
    <td><%= post.author.username %><td>
    <td><%= post.comments.count %><td>
  </tr>
<% end %>
</table>

<%= paginate @posts %>

app/views/posts/new.html.erb
<td><%= link_to 'Back to posts', posts_path %><td>
<br>
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, placeholder: "title" %>
  <%= f.label :body %>
  <%= f.text_area :body, placeholder: "body" %>
  <%= f.label :tags %>
  <%= f.text_field :tag_names_array, {value: @post.tag_names_with_commas, placeholder: "tags"} %>
  <%= f.submit "Create Post" %>
<% end %>

app/views/posts/show.html.erb
<td><%= link_to 'Back to posts', posts_path %><td>
<br>
<% if PostsUpdatePolicy.update?(current_user, @post)%>
  <%= link_to 'Edit post', edit_post_path_url(@post.id) %>
<% end %>
<br> 
<% if PostsDeletionPolicy.delete?(current_user, @post)%>
  <%= form_with url: delete_post_path_url(@post.id), method: :delete do |form| %>
    <%= form.submit "Delete post", class: "link-button" %>
  <% end %>
<% end %>
<br> 
<h1><%= @post.title%></h1>
<br> 
<h4>
  Author: 
  <%= @post.author.username%>
</h4>
<h4>
  Tags: 
  <%= @post.tags.map(&:name).join(', ') %>
</h4>
<%= @post.body%>
<table class="table table-hover">
<% if @post.comments.any? %>
  <tr>
    <th>Author</th>
    <th>Comment</th>
  </tr>
  <% @post.comments.order("created_at DESC").each do |comment| %>
    <tr>
      <td><%= comment.author.username %><td>
      <td><%= comment.body %><td>
    </tr>
  <% end %>
<% else %>
  There are no comments yet.
<% end %>
</table>

<%= form_with url: comments_path, method: :post do |form| %>
  <%= form.hidden_field :post_id, value: @post.id %>
  <%= form.text_area :body, placeholder: "body" %>
  <%= form.submit "Create comment", class: "link-button" %>
<% end %>